#+TITLE: SARIT’s eXist-db web application

This repository collects the various modules needed to run
http://sarit.indology.info.

It is not yet possible to do a completely automated install, but this
guide should make it as painless as currently possible (at least for a
typical Debian testing system; see [[file:docker-sarit-app/README.org]]
for a click and go solution).

You can compile and run a local version like this (your ~JAVA_HOME~
might be different, though):

#+BEGIN_SRC sh
git clone --recursive https://github.com/sarit/sarit-existdb.git
cd ./sarit-existdb/
./bin/build.sh
cd ./exist/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre java -jar start.jar jetty
#+END_SRC


1) https://github.com/sarit/exist: eXist-db with a patch to enable
   case-sensitive searching
2) https://github.com/sarit/lucene-transcoding-analyzer: a Java
   library to deal with SLP1 encoding.
   1) Depends on http://sanskritlibrary.org/software/transcodeFile.zip
3) https://github.com/sarit/sarit-transliteration-exist-module: an
   eXist-db module that uses the lucene-transcoding-analyzer
4) http://gitlab.exist-db.org/tei-publisher/tei-publisher-lib.git: TEI
   Publisher library, for formatting and display
5) A module for PDF functionality:
   http://exist-db.org/exist/apps/public-repo/public/expath-pdf-exist-lib-0.0.4.xar
6) http://demo.exist-db.org/exist/apps/public-repo/public/tei-pm-1.1.2.xar
7) https://github.com/sarit/sarit-data: the data for the webapp
8) https://github.com/sarit/sarit-pm: the user interface of the webapp



* Manual installation (for testing new features)

** System-wide requirements

#+BEGIN_SRC sh
sudo aptitude install openjdk-8-jdk maven nodejs npm
#+END_SRC

** eXist-db

*CAREFUL, this WILL delete your data!*

#+BEGIN_SRC sh :results raw output
cd ./exist/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ./build.sh clean-all
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ./build.sh
#+END_SRC

*** Test startup 

#+BEGIN_SRC sh
cd ./exist/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ./bin/startup.sh
#+END_SRC


*** Install dependencies from dashboard, http://127.0.0.1:8080/exist/apps/dashboard/index.html

1) tei-publisher-lib: http://gitlab.exist-db.org/tei-publisher/tei-publisher-lib



** lucene-transcoding-analyzer and sarit-transliteration-exist-module

#+BEGIN_SRC sh
  [ ! -f transcodeFile.zip ] && wget http://sanskritlibrary.org/software/transcodeFile.zip
  unzip transcodeFile.zip
  mvn install:install-file -Dfile=./TranscodeFile/dist/lib/SanskritLibrary.jar -DgroupId=org.sanskritlibrary -DartifactId=sl -Dversion=0.1 -Dpackaging=jar
  cd ./lucene-transcoding-analyzer/
  mvn clean install -DskipTests
  cd ../sarit-transliteration-exist-module/
  mvn package
#+END_SRC

The last step should produce a file called something like
~sarit-transliteration-exist-module-0.0.8.xar~ in
~./sarit-transliteration-exist-module/targets/~.  You have to install
this via the dashboard,
http://127.0.0.1:8080/exist/apps/dashboard/index.html.

** sarit-data

#+BEGIN_SRC sh
cd ./sarit-data/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ../exist/build.sh
#+END_SRC

This should give you something like
~./sarit-data/build/sarit-data-0.1.xar~, which you can install via the
dashboard, http://127.0.0.1:8080/exist/apps/dashboard/index.html.

You might also want to update the data collection, by visiting:
http://127.0.0.1:8080/exist/apps/sarit-data/index.html.


** sarit-pm

(Note for Debian users: using npm requires node-legacy package, ~sudo
aptitude install nodejs-legacy~.)

#+BEGIN_SRC sh
cd ./sarit-pm/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ../exist/build.sh
#+END_SRC

This should give you something like
~./sarit-pm/build/sarit-pm-0.2.xar~, which you can install via the
dashboard, http://127.0.0.1:8080/exist/apps/dashboard/index.html.


Now, check if it worked: 

- http://127.0.0.1:8080/exist/apps/sarit-pm/works/
- or http://127.0.0.1:8080/exist/apps/sarit-pm/works/search.html?query=*lak%E1%B9%A3a%E1%B9%87*+AND+*pratyak%E1%B9%A3*&field=text&tei-target=tei-text&work-authors=all

** With ~autodeploy/~


#+BEGIN_SRC bash
  git clone --recursive --shallow-submodules --depth 1 https://github.com/sarit/sarit-existdb.git
  cd ./sarit-existdb/
  [ ! -f transcodeFile.zip ] && wget http://sanskritlibrary.org/software/transcodeFile.zip
  unzip transcodeFile.zip
  mvn install:install-file -Dfile=./TranscodeFile/dist/lib/SanskritLibrary.jar -DgroupId=org.sanskritlibrary -DartifactId=sl -Dversion=0.1 -Dpackaging=jar
  cd ./lucene-transcoding-analyzer/
  mvn clean install -DskipTests
  cd ../exist/
  JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ./build.sh
  cd ../sarit-transliteration-exist-module/
  mvn package
  cp ./target/sarit-transliteration-exist-module-0.0.8.xar ../exist/autodeploy/
  cd ../sarit-data/
  JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ../exist/build.sh
  cp ./build/sarit-data-0.1.xar ../exist/autodeploy/sarit-data-0.1.xar
  cd ../sarit-pm/
  JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ../exist/build.sh
  cp ./build/sarit-pm-0.2.xar ../exist/autodeploy/sarit-pm-0.2.xar
  cd ../exist/autodeploy/
  wget http://demo.exist-db.org/exist/apps/public-repo/public/tei-publisher-lib-2.0.3.xar \
       http://exist-db.org/exist/apps/public-repo/public/expath-pdf-exist-lib-0.0.4.xar \
       http://demo.exist-db.org/exist/apps/public-repo/public/tei-pm-1.1.2.xar
  cd ../
  # start exist to install autodeploy ... takes long!
  JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre ./bin/startup.sh
#+END_SRC

You can check logs for the autodeployment in
~./exist/webapp/WEB-INF/logs/expath-repo.log~.



* Automatic installation

- To be done when manual works well.


* Important Bugs 
<<exist-bugs>>

These bugs make it necessary (or at least easier) to compile the SARIT
webapp on the host where it is being run:

1) https://github.com/eXist-db/exist/issues/1382: makes it difficult to dockerize
   1) more precisely, we can’t just build a dist from a locally installed version
   2) possible solution: build to same path as in docker?
2) https://github.com/eXist-db/exist/issues/1352
   1) makes it impossible to produce a .war file (that could easily be deployed)

* Footnotes

[fn:1] 

